# Generated by Django 4.1.3 on 2022-11-19 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Place", models.CharField(max_length=125, null=True)),
                ("birth_date", models.DateField(null=True)),
                ("status", models.CharField(max_length=50, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=30
                    ),
                ),
                ("overview", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settingss",
                "db_table": "User_settings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfileSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_img", models.ImageField(null=True, upload_to="Back")),
                (
                    "profile_img",
                    models.ImageField(
                        default="Profile/placeholder.jpg", upload_to="Profile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
                "db_table": "User_Profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=125)),
                ("url", models.CharField(default=None, max_length=125, null=True)),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user_Notification",
                "verbose_name_plural": "user_Notifications",
                "db_table": "user_Notification",
                "ordering": ("-time",),
                "managed": True,
            },
        ),
    ]
