"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7u1fwbfyl%ilcy^^^9&&w&9e&ydcq%wf(rop=v^+bs+uz72xaw"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
]

INTERNAL_IPS = [
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "ckeditor_uploader",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "blog",
    "debug_toolbar",
    "django_filters",
    "ckeditor",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "website.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "website.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "Blog.db",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = BASE_DIR / "collect"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGIN_URL = "/user/login"
LOGIN_REDIRECT_URL = "/user"

# Ckeditor
CKEDITOR_UPLOAD_PATH = "uploads"
CKEDITOR_CONFIGS = {
    "aws": {
        "toolbar": "full",
    },
    "default": {
        "skin": "n1theme",
        "toolbar": "Custom",
        "width": "auto",
        "toolbar_Custom": [
            {
                "name": "format",
                "items": ["Styles", "Format", "Font", "FontSize"],
            },
            {
                "name": "Basic",
                "items": ["Bold", "Italic", "Underline", "Strike"],
            },
            {
                "name": "list",
                "items": ["NumberedList", "BulletList", "-", "Outdent", "Indent", "-"],
            },
            {
                "name": "Textalign",
                "items": [
                    "JustifyLeft",
                    "JustifyRight",
                    "JustifyCenter",
                    "JustifyBlock",
                ],
            },
            {
                "name": "link",
                "items": ["Link", "Unlink", "Anchor"],
            },
            {
                "name": "textcolor",
                "items": ["TextColor", "BGColor"],
            },
            {
                "name": "format",
                "items": ["RemoveFormat", "Source"],
            },
            {
                "name": "tools",
                "items": ["ShowBlocks", "Preview", "Maximize"],
            },
        ],
    },
}

# Media Url
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# cache
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.redis.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379",
#         "TIMEOUT": 60,
#         "OPTIONS": {
#             "db": "10",
#             "parser_class": "redis.connection.PythonParser",
#             "pool_class": "redis.BlockingConnectionPool",
#         },
#     }
# }


# Email
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_HOST = ""
# EMAIL_PORT = 2500
EMAIL_HOST_USER = "madhu"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
