# Generated by Django 4.1.3 on 2022-11-19 10:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagname", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tags",
                "verbose_name_plural": "Tagss",
                "db_table": "blog_tags",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("title", models.CharField(max_length=50)),
                (
                    "blog_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("post_image", models.ImageField(null=True, upload_to="blogs")),
                ("content", ckeditor.fields.RichTextField(blank=True)),
                ("tag", models.CharField(max_length=50)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Publish", "Publish"),
                            ("Private", "Private"),
                        ],
                        default="Private",
                        max_length=30,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "blog_Posts",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("comment", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.posts"
                    ),
                ),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
    ]
